version: '3.4'

networks:
  dev:
    driver: bridge

services:
  ahstats:
    image: 'ahstats'
    depends_on:
      - "ahstats_db"
    container_name: ahstats
    ports:
      - "5115:8080"
    networks:
      - dev
    environment:
      - WowClient__ClientId
      - WowClient__ClientSecret

  ahstats_db:
    image: postgres:latest
    container_name: ahstats_db
    environment:
      - POSTGRES_USER=ahstats
      - POSTGRES_PASSWORD=ahstats
      - POSTGRES_DB=ahstats
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /opt/ahstats/postgres:/var/lib/postgresql/data/
    networks:
      - dev